"""create_initial_flash_flood_tables

Revision ID: 4c9d7307d300
Revises: 
Create Date: 2026-09-16 15:56:29.379907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9d7307d300'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.Enum('FLASH_FLOOD', 'RIVER_RISE', 'SOIL_SATURATION', 'CLOUDBURST', 'EVACUATION_WARNING', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('ADVISORY', 'WATCH', 'WARNING', 'EMERGENCY', name='alertseverity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', name='alertstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alert_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('evacuation_centers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy', sa.Integer(), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('facilities', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evacuation_centers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evacuation_centers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evacuation_centers_name'), ['name'], unique=False)

    op.create_table('historical_flood_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('maximum_rainfall', sa.Float(), nullable=False),
    sa.Column('maximum_water_level', sa.Float(), nullable=False),
    sa.Column('affected_area', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_flood_events', schema=None) as batch_op:
        batch_op.create_index('idx_historical_event_start_sev', ['start_time', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_flood_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_flood_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_flood_events_start_time'), ['start_time'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'RESEARCHER', 'RESPONSE_TEAM', 'GOVERNMENT_OFFICIAL', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('watersheds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('area_sq_km', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('geometry', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watersheds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watersheds_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_watersheds_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watersheds_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_watersheds_risk_level'), ['risk_level'], unique=False)

    op.create_table('citizen_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.Enum('WATER_OVERFLOW', 'RIVER_BANK_EROSION', 'ROAD_BLOCKED', 'LANDSLIDE', 'STRUCTURAL_DAMAGE', 'OTHER', name='citizenreporttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.create_index('idx_citizen_report_status_created', ['verification_status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_reports_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_reports_verification_status'), ['verification_status'], unique=False)

    op.create_table('flood_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watershed_id', sa.Integer(), nullable=False),
    sa.Column('prediction_time', sa.DateTime(), nullable=False),
    sa.Column('forecast_for', sa.DateTime(), nullable=False),
    sa.Column('predicted_water_level', sa.Float(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['watershed_id'], ['watersheds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flood_predictions', schema=None) as batch_op:
        batch_op.create_index('idx_pred_watershed_forecast', ['watershed_id', 'forecast_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_flood_predictions_forecast_for'), ['forecast_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_flood_predictions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flood_predictions_prediction_time'), ['prediction_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_flood_predictions_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_flood_predictions_watershed_id'), ['watershed_id'], unique=False)

    op.create_table('sensors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sensor_type', sa.Enum('RAINFALL', 'RIVER_LEVEL', 'SOIL_MOISTURE', 'WEATHER', 'MULTI_SENSOR', name='sensortype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('watershed_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'OFFLINE', name='sensorstatus'), nullable=False),
    sa.Column('battery_level', sa.Float(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['watershed_id'], ['watersheds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensors_sensor_code'), ['sensor_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_sensors_sensor_type'), ['sensor_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensors_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensors_watershed_id'), ['watershed_id'], unique=False)

    op.create_table('rainfall_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rainfall_readings', schema=None) as batch_op:
        batch_op.create_index('idx_rainfall_sensor_timestamp', ['sensor_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_rainfall_readings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rainfall_readings_sensor_id'), ['sensor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rainfall_readings_timestamp'), ['timestamp'], unique=False)

    op.create_table('river_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('water_level_m', sa.Float(), nullable=False),
    sa.Column('flow_rate', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('river_readings', schema=None) as batch_op:
        batch_op.create_index('idx_river_sensor_timestamp', ['sensor_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_river_readings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_river_readings_sensor_id'), ['sensor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_river_readings_timestamp'), ['timestamp'], unique=False)

    op.create_table('sensor_health_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('battery_level', sa.Float(), nullable=False),
    sa.Column('signal_strength', sa.Float(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'OFFLINE', name='sensorstatus'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_health_logs', schema=None) as batch_op:
        batch_op.create_index('idx_sensor_health_sensor_recorded', ['sensor_id', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_health_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_health_logs_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_health_logs_sensor_id'), ['sensor_id'], unique=False)

    op.create_table('soil_moisture_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('moisture_percentage', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('soil_moisture_readings', schema=None) as batch_op:
        batch_op.create_index('idx_soil_moisture_sensor_timestamp', ['sensor_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_soil_moisture_readings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_soil_moisture_readings_sensor_id'), ['sensor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_soil_moisture_readings_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_moisture_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soil_moisture_readings_timestamp'))
        batch_op.drop_index(batch_op.f('ix_soil_moisture_readings_sensor_id'))
        batch_op.drop_index(batch_op.f('ix_soil_moisture_readings_id'))
        batch_op.drop_index('idx_soil_moisture_sensor_timestamp')

    op.drop_table('soil_moisture_readings')
    with op.batch_alter_table('sensor_health_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_health_logs_sensor_id'))
        batch_op.drop_index(batch_op.f('ix_sensor_health_logs_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_sensor_health_logs_id'))
        batch_op.drop_index('idx_sensor_health_sensor_recorded')

    op.drop_table('sensor_health_logs')
    with op.batch_alter_table('river_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_river_readings_timestamp'))
        batch_op.drop_index(batch_op.f('ix_river_readings_sensor_id'))
        batch_op.drop_index(batch_op.f('ix_river_readings_id'))
        batch_op.drop_index('idx_river_sensor_timestamp')

    op.drop_table('river_readings')
    with op.batch_alter_table('rainfall_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rainfall_readings_timestamp'))
        batch_op.drop_index(batch_op.f('ix_rainfall_readings_sensor_id'))
        batch_op.drop_index(batch_op.f('ix_rainfall_readings_id'))
        batch_op.drop_index('idx_rainfall_sensor_timestamp')

    op.drop_table('rainfall_readings')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensors_watershed_id'))
        batch_op.drop_index(batch_op.f('ix_sensors_status'))
        batch_op.drop_index(batch_op.f('ix_sensors_sensor_type'))
        batch_op.drop_index(batch_op.f('ix_sensors_sensor_code'))
        batch_op.drop_index(batch_op.f('ix_sensors_id'))

    op.drop_table('sensors')
    with op.batch_alter_table('flood_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flood_predictions_watershed_id'))
        batch_op.drop_index(batch_op.f('ix_flood_predictions_risk_level'))
        batch_op.drop_index(batch_op.f('ix_flood_predictions_prediction_time'))
        batch_op.drop_index(batch_op.f('ix_flood_predictions_id'))
        batch_op.drop_index(batch_op.f('ix_flood_predictions_forecast_for'))
        batch_op.drop_index('idx_pred_watershed_forecast')

    op.drop_table('flood_predictions')
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citizen_reports_verification_status'))
        batch_op.drop_index(batch_op.f('ix_citizen_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_citizen_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_citizen_reports_id'))
        batch_op.drop_index(batch_op.f('ix_citizen_reports_created_at'))
        batch_op.drop_index('idx_citizen_report_status_created')

    op.drop_table('citizen_reports')
    with op.batch_alter_table('watersheds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watersheds_risk_level'))
        batch_op.drop_index(batch_op.f('ix_watersheds_name'))
        batch_op.drop_index(batch_op.f('ix_watersheds_id'))
        batch_op.drop_index(batch_op.f('ix_watersheds_code'))

    op.drop_table('watersheds')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('historical_flood_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_flood_events_start_time'))
        batch_op.drop_index(batch_op.f('ix_historical_flood_events_severity'))
        batch_op.drop_index(batch_op.f('ix_historical_flood_events_id'))
        batch_op.drop_index('idx_historical_event_start_sev')

    op.drop_table('historical_flood_events')
    with op.batch_alter_table('evacuation_centers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evacuation_centers_name'))
        batch_op.drop_index(batch_op.f('ix_evacuation_centers_id'))

    op.drop_table('evacuation_centers')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_expires_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))
        batch_op.drop_index('idx_alert_status_created')

    op.drop_table('alerts')
    # ### end Alembic commands ###
